/*#include "../../Source/Code/Compile/CE Command.cpp"
#include "../../Source/Code/Compile/CE Compiler.cpp"
#include "../../Source/Code/Compile/CE Environment.cpp"
#include "../../Source/Code/Compile/CE Expression.cpp"
#include "../../Source/Code/CE Code Col Line.cpp"
#include "../../Source/Code/CE Editor C++.cpp"
#include "../../Source/Code/CE Editor GUI.cpp"
#include "../../Source/Code/CE Editor IO.cpp"
#include "../../Source/Code/CE Editor Parser.cpp"
#include "../../Source/Code/CE Editor Sources.cpp"
#include "../../Source/Code/CE Find.cpp"
#include "../../Source/Code/CE Item.cpp"
#include "../../Source/Code/CE Macro.cpp"
#include "../../Source/Code/CE Parser.cpp"
#include "../../Source/Code/CE Source C++.cpp"
#include "../../Source/Code/CE Source Edit.cpp"
#include "../../Source/Code/CE Source GUI.cpp"
#include "../../Source/Code/CE Source Preprocessor.cpp"
#include "../../Source/Code/CE Source Suggestions.cpp"
#include "../../Source/Code/CE Source.cpp"
#include "../../Source/Code/CE Symbol.cpp"
#include "../../Source/Code/CE Token.cpp"
#include "../../Source/Code/CE.cpp"
*/