/*
#include "../../Source/Shaders/Ambient.cpp"
#include "../../Source/Shaders/Ambient Occlusion.cpp"
#include "../../Source/Shaders/Behind.cpp"
#include "../../Source/Shaders/Blend.cpp"
#include "../../Source/Shaders/Blend Light.cpp"
#include "../../Source/Shaders/Deferred.cpp"
#include "../../Source/Shaders/Depth of Field.cpp"
#include "../../Source/Shaders/Early Z.cpp"
#include "../../Source/Shaders/Forward.cpp"
#include "../../Source/Shaders/Fur.cpp"
#include "../../Source/Shaders/Hdr.cpp"
#include "../../Source/Shaders/Layered Clouds.cpp"
#include "../../Source/Shaders/Main.cpp"
#include "../../Source/Shaders/Motion Blur.cpp"
#include "../../Source/Shaders/Overlay.cpp"
#include "../../Source/Shaders/Position.cpp"
#include "../../Source/Shaders/Set Color.cpp"
#include "../../Source/Shaders/Simple.cpp"
#include "../../Source/Shaders/Tattoo.cpp"
#include "../../Source/Shaders/Volumetric Clouds.cpp"
#include "../../Source/Shaders/Volumetric Lights.cpp"
#include "../../Source/Shaders/Water.cpp"
#include "../../Source/Shaders/World Editor.cpp"
*/