LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE       := fdk-aac
LOCAL_CFLAGS       := -I../lib/libAACdec/include -I../lib/libAACenc/include -I../lib/libFDK/include -I../lib/libMpegTPDec/include -I../lib/libMpegTPEnc/include -I../lib/libPCMutils/include -I../lib/libSBRdec/include -I../lib/libSBRenc/include -I../lib/libSYS/include -O3 -fshort-wchar -ffast-math -fomit-frame-pointer
LOCAL_CPPFLAGS     := -I../lib/libAACdec/include -I../lib/libAACenc/include -I../lib/libFDK/include -I../lib/libMpegTPDec/include -I../lib/libMpegTPEnc/include -I../lib/libPCMutils/include -I../lib/libSBRdec/include -I../lib/libSBRenc/include -I../lib/libSYS/include -O3 -fshort-wchar -ffast-math -fomit-frame-pointer
LOCAL_CPP_FEATURES := # rtti exceptions
LOCAL_ARM_NEON     := true # force NEON usage for all files
LOCAL_SRC_FILES    := \
   ../../lib/libAACdec/src/aac_ram.cpp \
   ../../lib/libAACdec/src/aac_rom.cpp \
   ../../lib/libAACdec/src/aacdec_drc.cpp \
   ../../lib/libAACdec/src/aacdec_hcr.cpp \
   ../../lib/libAACdec/src/aacdec_hcr_bit.cpp \
   ../../lib/libAACdec/src/aacdec_hcrs.cpp \
   ../../lib/libAACdec/src/aacdec_pns.cpp \
   ../../lib/libAACdec/src/aacdec_tns.cpp \
   ../../lib/libAACdec/src/aacdecoder.cpp \
   ../../lib/libAACdec/src/aacdecoder_lib.cpp \
   ../../lib/libAACdec/src/block.cpp \
   ../../lib/libAACdec/src/channel.cpp \
   ../../lib/libAACdec/src/channelinfo.cpp \
   ../../lib/libAACdec/src/conceal.cpp \
   ../../lib/libAACdec/src/ldfiltbank.cpp \
   ../../lib/libAACdec/src/pulsedata.cpp \
   ../../lib/libAACdec/src/rvlc.cpp \
   ../../lib/libAACdec/src/rvlcbit.cpp \
   ../../lib/libAACdec/src/rvlcconceal.cpp \
   ../../lib/libAACdec/src/stereo.cpp \
   ../../lib/libAACenc/src/aacenc.cpp \
   ../../lib/libAACenc/src/aacenc_lib.cpp \
   ../../lib/libAACenc/src/aacenc_pns.cpp \
   ../../lib/libAACenc/src/aacEnc_ram.cpp \
   ../../lib/libAACenc/src/aacEnc_rom.cpp \
   ../../lib/libAACenc/src/aacenc_tns.cpp \
   ../../lib/libAACenc/src/adj_thr.cpp \
   ../../lib/libAACenc/src/band_nrg.cpp \
   ../../lib/libAACenc/src/bandwidth.cpp \
   ../../lib/libAACenc/src/bit_cnt.cpp \
   ../../lib/libAACenc/src/bitenc.cpp \
   ../../lib/libAACenc/src/block_switch.cpp \
   ../../lib/libAACenc/src/channel_map.cpp \
   ../../lib/libAACenc/src/chaosmeasure.cpp \
   ../../lib/libAACenc/src/dyn_bits.cpp \
   ../../lib/libAACenc/src/grp_data.cpp \
   ../../lib/libAACenc/src/intensity.cpp \
   ../../lib/libAACenc/src/line_pe.cpp \
   ../../lib/libAACenc/src/metadata_compressor.cpp \
   ../../lib/libAACenc/src/metadata_main.cpp \
   ../../lib/libAACenc/src/ms_stereo.cpp \
   ../../lib/libAACenc/src/noisedet.cpp \
   ../../lib/libAACenc/src/pnsparam.cpp \
   ../../lib/libAACenc/src/pre_echo_control.cpp \
   ../../lib/libAACenc/src/psy_configuration.cpp \
   ../../lib/libAACenc/src/psy_main.cpp \
   ../../lib/libAACenc/src/qc_main.cpp \
   ../../lib/libAACenc/src/quantize.cpp \
   ../../lib/libAACenc/src/sf_estim.cpp \
   ../../lib/libAACenc/src/spreading.cpp \
   ../../lib/libAACenc/src/tonality.cpp \
   ../../lib/libAACenc/src/transform.cpp \
   ../../lib/libFDK/src/autocorr2nd.cpp \
   ../../lib/libFDK/src/dct.cpp \
   ../../lib/libFDK/src/FDK_bitbuffer.cpp \
   ../../lib/libFDK/src/FDK_core.cpp \
   ../../lib/libFDK/src/FDK_crc.cpp \
   ../../lib/libFDK/src/FDK_hybrid.cpp \
   ../../lib/libFDK/src/FDK_tools_rom.cpp \
   ../../lib/libFDK/src/FDK_trigFcts.cpp \
   ../../lib/libFDK/src/fft.cpp \
   ../../lib/libFDK/src/fft_rad2.cpp \
   ../../lib/libFDK/src/fixpoint_math.cpp \
   ../../lib/libFDK/src/mdct.cpp \
   ../../lib/libFDK/src/qmf.cpp \
   ../../lib/libFDK/src/scale.cpp \
   ../../lib/libMpegTPDec/src/tpdec_adif.cpp \
   ../../lib/libMpegTPDec/src/tpdec_adts.cpp \
   ../../lib/libMpegTPDec/src/tpdec_asc.cpp \
   ../../lib/libMpegTPDec/src/tpdec_drm.cpp \
   ../../lib/libMpegTPDec/src/tpdec_latm.cpp \
   ../../lib/libMpegTPDec/src/tpdec_lib.cpp \
   ../../lib/libMpegTPEnc/src/tpenc_adif.cpp \
   ../../lib/libMpegTPEnc/src/tpenc_adts.cpp \
   ../../lib/libMpegTPEnc/src/tpenc_asc.cpp \
   ../../lib/libMpegTPEnc/src/tpenc_latm.cpp \
   ../../lib/libMpegTPEnc/src/tpenc_lib.cpp \
   ../../lib/libPCMutils/src/limiter.cpp \
   ../../lib/libPCMutils/src/pcmutils_lib.cpp \
   ../../lib/libSBRdec/src/env_calc.cpp \
   ../../lib/libSBRdec/src/env_dec.cpp \
   ../../lib/libSBRdec/src/env_extr.cpp \
   ../../lib/libSBRdec/src/huff_dec.cpp \
   ../../lib/libSBRdec/src/lpp_tran.cpp \
   ../../lib/libSBRdec/src/psbitdec.cpp \
   ../../lib/libSBRdec/src/psdec.cpp \
   ../../lib/libSBRdec/src/psdec_hybrid.cpp \
   ../../lib/libSBRdec/src/sbr_crc.cpp \
   ../../lib/libSBRdec/src/sbr_deb.cpp \
   ../../lib/libSBRdec/src/sbr_dec.cpp \
   ../../lib/libSBRdec/src/sbr_ram.cpp \
   ../../lib/libSBRdec/src/sbr_rom.cpp \
   ../../lib/libSBRdec/src/sbrdec_drc.cpp \
   ../../lib/libSBRdec/src/sbrdec_freq_sca.cpp \
   ../../lib/libSBRdec/src/sbrdecoder.cpp \
   ../../lib/libSBRenc/src/bit_sbr.cpp \
   ../../lib/libSBRenc/src/code_env.cpp \
   ../../lib/libSBRenc/src/env_bit.cpp \
   ../../lib/libSBRenc/src/env_est.cpp \
   ../../lib/libSBRenc/src/fram_gen.cpp \
   ../../lib/libSBRenc/src/invf_est.cpp \
   ../../lib/libSBRenc/src/mh_det.cpp \
   ../../lib/libSBRenc/src/nf_est.cpp \
   ../../lib/libSBRenc/src/ps_bitenc.cpp \
   ../../lib/libSBRenc/src/ps_encode.cpp \
   ../../lib/libSBRenc/src/ps_main.cpp \
   ../../lib/libSBRenc/src/resampler.cpp \
   ../../lib/libSBRenc/src/sbr_encoder.cpp \
   ../../lib/libSBRenc/src/sbr_misc.cpp \
   ../../lib/libSBRenc/src/sbr_ram_.cpp \
   ../../lib/libSBRenc/src/sbr_rom_.cpp \
   ../../lib/libSBRenc/src/sbrenc_freq_sca.cpp \
   ../../lib/libSBRenc/src/ton_corr.cpp \
   ../../lib/libSBRenc/src/tran_det.cpp \
   ../../lib/libSYS/src/conv_string.cpp \
   ../../lib/libSYS/src/genericStds.cpp \
   ../../lib/libSYS/src/wav_file.cpp

include $(BUILD_STATIC_LIBRARY)
