rmdir /s /q "lib\data"
rmdir /s /q "lib\docs"
rmdir /s /q "lib\examples"
rmdir /s /q "lib\test"
rmdir /s /q "lib\build3\vs2010\.vs"
rmdir /s /q "lib\build3\vs2010\ARM"
rmdir /s /q "lib\build3\vs2010\Debug"
rmdir /s /q "lib\build3\vs2010\Emscripten"
rmdir /s /q "lib\build3\vs2010\Generated Files"
rmdir /s /q "lib\build3\vs2010\obj"
rmdir /s /q "lib\build3\vs2010\Release"
rmdir /s /q "lib\build3\vs2010\Release Universal"
rmdir /s /q "lib\build3\vs2010\x64"

"Android 3) Clean.bat"