del "lib\visualc\VS2010\ARM\Release\*.obj"
del "lib\visualc\VS2010\ARM\Release\*.cache"
del "lib\visualc\VS2010\ARM\Release\*.xml"
del "lib\visualc\VS2010\ARM\Release\*.resfiles"
del "lib\visualc\VS2010\ARM\Release\*.txt"
del "lib\visualc\VS2010\ARM\Release\*.intermediate"
del "lib\visualc\VS2010\ARM\Release\mbedTLS\*.pri"
rmdir /s /q "lib\visualc\VS2010\.vs"
rmdir /s /q "lib\visualc\VS2010\Debug"
rmdir /s /q "lib\visualc\VS2010\x64\Debug"
rmdir /s /q "lib\visualc\VS2010\Generated Files"
rmdir /s /q "lib\visualc\VS2010\Release\mbedTLS"
rmdir /s /q "lib\visualc\VS2010\ARM\Release\mbedTLS.tlog"
